name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'
          extended: true

      - name: Build
        run: hugo --minify --baseURL https://radiozed.github.io/

      - name: Commit static files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Build static files" || echo "No changes"
          git push origin main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}